phy: phy-mtk-dp: drop unused variables
Recent changes in driver added unused variables causing build warnings:

drivers/phy/mediatek/phy-mtk-dp.c: In function ‘mtk_dp_phy_set_digital_drv_params’:
drivers/phy/mediatek/phy-mtk-dp.c:332:16: error: unused variable ‘ret’ [-Werror=unused-variable]
  332 |         int i, ret;
      |                ^~~
drivers/phy/mediatek/phy-mtk-dp.c: In function ‘mtk_dp_phy_init’:
drivers/phy/mediatek/phy-mtk-dp.c:348:24: error: unused variable ‘dev’ [-Werror=unused-variable]
  348 |         struct device *dev = &phy->dev;
      |                        ^~~
drivers/phy/mediatek/phy-mtk-dp.c: In function ‘mtk_dp_phy_disable_all_lanes’:
drivers/phy/mediatek/phy-mtk-dp.c:457:13: error: unused variable ‘ret’ [-Werror=unused-variable]
  457 |         int ret;
      |             ^~~

Drop these to fix these

Signed-off-by: Vinod Koul <vkoul@kernel.org>